swap_ec_rw: Support giving a raw EC RW image
For the EC supporting only a single firmware copy, their EC image
has no FMAP and no traditional sections, like EC_RW, RW_FWID.

Add support to accept a raw EC RW image. The version file can be
optionally added to the CBFS.

And make the EC hash always recalculated.

BUG=b:388903762
TEST=make runtestscripts
BRANCH=none

Change-Id: Id8e96832c0607b700b17e86e3402cd4856cf5b37
Signed-off-by: Wai-Hong Tam <waihong@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/6489288
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Commit-Queue: ChromeOS Auto Retry <chromeos-auto-retry@chromeos-bot.iam.gserviceaccount.com>

diff --git a/scripts/image_signing/swap_ec_rw b/scripts/image_signing/swap_ec_rw
--- a/scripts/image_signing/swap_ec_rw
+++ b/scripts/image_signing/swap_ec_rw
@@ -17,6 +17,8 @@ DEFINE_string image "" "The AP firmware file (e.g 'image-steelix.bin') to swap o
 DEFINE_string ec "" "The EC firmware file (e.g 'ec.bin')" e
 DEFINE_string ec_config "" "The EC config file (default is 'ec.config')"
 DEFINE_string ap_for_ec "" "The AP firmware file (e.g 'image-steelix.bin') as source of EC firmware file" a
+DEFINE_string raw_ecrw "" "The raw EC RW file (e.g. 'ec.RW.flat')" r
+DEFINE_string ec_ver "" "The EC version file (e.g. 'ec.version')" v
 
 # Parse command line.
 FLAGS "$@" || exit 1
@@ -69,20 +71,15 @@ cbfstool_try_remove() {
 
 extract_ecrw_files_from_ap() {
   local ecrw_file=$1
-  local ecrw_hash_file=$2
-  local ecrw_ver_file=$3
-  local ecrw_config_file=$4
-  local ap_for_ec_file=$5
+  local ecrw_ver_file=$2
+  local ecrw_config_file=$3
+  local ap_for_ec_file=$4
 
   local region="${FMAP_REGIONS[0]}"
 
   cbfstool "${ap_for_ec_file}" extract -r "${region}" -n "${CBFS_ECRW_NAME}" \
     -f "${ecrw_file}"
   info "EC RW extracted to ${ecrw_file}"
-
-  cbfstool "${ap_for_ec_file}" extract -r "${region}" \
-    -n "${CBFS_ECRW_HASH_NAME}" -f "${ecrw_hash_file}"
-  info "EC RW hash extracted to ${ecrw_hash_file}"
 
   cbfstool_try_extract "${ap_for_ec_file}" "${region}" \
     "${CBFS_ECRW_VERSION_NAME}" "${ecrw_ver_file}" \
@@ -95,18 +92,14 @@ extract_ecrw_files_from_ap() {
 
 extract_ecrw_files_from_ec() {
   local ecrw_file=$1
-  local ecrw_hash_file=$2
-  local ecrw_ver_file=$3
-  local ec_file=$4
+  local ecrw_ver_file=$2
+  local ec_file=$3
 
   if ! futility dump_fmap -x "${ec_file}" "RW_FW:${ecrw_file}" >/dev/null ; then
     info "Falling back to EC_RW section"
     futility dump_fmap -x "${ec_file}" "EC_RW:${ecrw_file}" >/dev/null
   fi
   info "EC RW extracted to ${ecrw_file}"
-
-  openssl dgst -sha256 -binary "${ecrw_file}" > "${ecrw_hash_file}"
-  info "EC RW hash saved to ${ecrw_hash_file}"
 
   futility dump_fmap -x "${ec_file}" "RW_FWID:${ecrw_ver_file}" >/dev/null
 }
@@ -116,6 +109,8 @@ swap_ecrw() {
   local ec_file=$2
   local ec_config_file=$3
   local ap_for_ec_file=$4
+  local raw_ecrw=$5
+  local ec_ver=$6
 
   local temp_dir
   local ecrw_file
@@ -140,20 +135,24 @@ swap_ecrw() {
   if [[ -n "${ec_file}" ]]; then
     extract_ecrw_files_from_ec \
       "${ecrw_file}" \
-      "${ecrw_hash_file}" \
       "${ecrw_ver_file}" \
       "${ec_file}"
     if [[ -n "${ec_config_file}" ]]; then
       ecrw_config_file="${ec_config_file}"
     fi
-  else
+  elif [[ -n "${ap_for_ec_file}" ]]; then
     extract_ecrw_files_from_ap \
       "${ecrw_file}" \
-      "${ecrw_hash_file}" \
       "${ecrw_ver_file}" \
       "${ecrw_config_file}" \
       "${ap_for_ec_file}"
+  else
+    ecrw_file="${raw_ecrw}"
+    ecrw_ver_file="${ec_ver}"
   fi
+
+  openssl dgst -sha256 -binary "${ecrw_file}" > "${ecrw_hash_file}"
+  info "EC RW hash is recalculated and saved to ${ecrw_hash_file}"
 
   for region in "${FMAP_REGIONS[@]}"
   do
@@ -220,13 +219,13 @@ main() {
     die "-i or --image are required."
   fi
 
-  if [[ -z "${FLAGS_ec}" ]] && [[ -z "${FLAGS_ap_for_ec}" ]]; then
+  has_ec=$([[ -n "${FLAGS_ec}" ]] && echo 1 || echo 0)
+  has_ap_for_ec=$([[ -n "${FLAGS_ap_for_ec}" ]] && echo 1 || echo 0)
+  has_raw_ecrw=$([[ -n "${FLAGS_raw_ecrw}" ]] && echo 1 || echo 0)
+
+  if [[ $((has_ec + has_ap_for_ec + has_raw_ecrw)) -ne 1 ]]; then
     flags_help
-    die "-e/--ec or -a/--ap_for_ec are required."
-  fi
-  if [[ -n "${FLAGS_ec}" ]] && [[ -n "${FLAGS_ap_for_ec}" ]]; then
-    flags_help
-    die "-e/--ec conflicts with -a/--ap_for_ec."
+    die "Exactly one of -e/--ec, -a/--ap_for_ec, or -r/--raw_ecrw is required."
   fi
 
   if [[ -n "${FLAGS_ec}" ]] &&
@@ -239,8 +238,17 @@ main() {
      [[ -n "${FLAGS_ec_config}" ]]; then
     die "-a/--ap_for_ec conflicts with --ec_config."
   fi
+  if [[ -n "${FLAGS_ec}" ]] &&
+     [[ -n "${FLAGS_ec_ver}" ]]; then
+    die "-e/--ec conflicts with --ec_ver."
+  fi
+  if [[ -n "${FLAGS_ap_for_ec}" ]] &&
+     [[ -n "${FLAGS_ec_ver}" ]]; then
+    die "-a/--ap_for_ec conflicts with --ec_ver."
+  fi
 
-  swap_ecrw "${FLAGS_image}" "${FLAGS_ec}" "${FLAGS_ec_config}" "${FLAGS_ap_for_ec}"
+  swap_ecrw "${FLAGS_image}" "${FLAGS_ec}" "${FLAGS_ec_config}" "${FLAGS_ap_for_ec}" \
+      "${FLAGS_raw_ecrw}" "${FLAGS_ec_ver}"
 }
 
 main "$@"
