Skip ec.config if there is no space
We want ec.config for test purposes, but the firmware will still work
fine without it. If there isn't room for the ec.config, then just omit
it.

BRANCH=None
BUG=b:478868222
TEST=swap_ec_rw --image image-gothrax.bin --ec ec.bin

Change-Id: If9d28e4070a6ffec85cd7594c2b63eed05adc5c9
Signed-off-by: Jeremy Bettis <jbettis@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/7517252
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Wai-Hong Tam <waihong@google.com>
Auto-Submit: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Julius Werner <jwerner@chromium.org>

diff --git a/scripts/image_signing/swap_ec_rw b/scripts/image_signing/swap_ec_rw
--- a/scripts/image_signing/swap_ec_rw
+++ b/scripts/image_signing/swap_ec_rw
@@ -239,9 +239,16 @@ swap_ecrw() {
     fi
     # Add ecrw.config if provided.
     if [[ -e "${ecrw_config_file}" ]]; then
-      cbfstool "${ap_file}" add -r "${region}" -t raw \
+      local output
+      if ! output="$(cbfstool "${ap_file}" add -r "${region}" -t raw \
         -c "${ecrw_comp_type}" -f "${ecrw_config_file}" \
-        -n "${CBFS_ECRW_CONFIG_NAME}"
+        -n "${CBFS_ECRW_CONFIG_NAME}" 2>&1)" ; then
+        if [[ "${output}" == *"Largest empty slot"* ]]; then
+          warn "Skipping ${CBFS_ECRW_CONFIG_NAME} due to insufficient space:"$'\n'"${output}"
+        else
+          die "Failed to add ${CBFS_ECRW_CONFIG_NAME} to CBFS:"$'\n'"${output}"
+        fi
+      fi
     else
       warn "${CBFS_ECRW_CONFIG_NAME} is missing from source file."
     fi
